### ISSUE TITLE
Highlighting issue with `static member access-modifier Foo(?x:string)`

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/fsharp-support#207] opened 2020-11-20 16:44 UTC
There is a single highlighting issue when this very specific combination of syntax is used:

```fs
type X = 
    static member private Foo(?x:bool) = ()
    //vs 
    static member private Foo(x:bool) = ()
```

The method braces get erroneously highlighted here

<img width="350" alt="Screenshot 2020-11-20 at 17 42 11" src="https://user-images.githubusercontent.com/4218809/99825785-c90aa800-2b57-11eb-8e6a-e2d2c057aa17.png">

**Comment by auduchinok** [comment] 2020-11-23 12:26
@NinoFloris Thanks for the report! It's fixed in [cd9b0b4](https://github.com/JetBrains/fsharp-support/commit/cd9b0b479158e260338080ba46b0d2104bf3eaa9).

The issue is FCS produces fake `OptionalParameter` attribute usages at such declarations, and our ignore heuristic didn't work well with access modifiers. The compiler issue is https://github.com/dotnet/fsharp/issues/3933.

**Closed by auduchinok** 2020-11-23 12:26 UTC
