### ISSUE TITLE
FSharp.sln (dotnet/fsharp) linked project items are not shown

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/fsharp-support#112] opened 2020-04-16 11:59 UTC
FSharp.sln (dotnet/fsharp) linked project items are not shown

<img width="269" alt="Screenshot 2020-04-16 at 13 56 36" src="https://user-images.githubusercontent.com/4218809/79453645-3f579280-7fea-11ea-95c8-5dc083245598.png">

The repro for this seems to be:

1. First run build.sh/build.cmd 
2. Only then load the project in Rider

Letting Rider handle the complete build causes all the folders and items to be added correctly to the project.

This is something I have run into multiple times already and it's very nasty to debug for a newcomer to a codebase like the compiler.

**Comment by saul** [comment] 2020-04-17 16:34
Dupe of https://github.com/JetBrains/fsharp-support/issues/49, which hasn't had any official recognition yet. I don't think this is an F# plugin issue, it's likely an issue with Rider itself. More likely to get a response on the Rider YouTrack

**Comment by auduchinok** [comment] 2020-04-26 20:12
@NinoFloris @saul Yes, it's a duplicate, thanks, I left a comment there. Basically, using `fcs/FSharp.Compiler.Service.sln` is way to go for now, and keeping a single target framework improves the perf. Let's continue the discussion in #49, thanks!

**Closed by auduchinok** 2020-04-26 20:12 UTC
