### ISSUE TITLE
Inlining Analyzer integration

### ISSUE THREAD

**Issue by wklm** [JetBrains/fsharp-support#5] opened 2017-12-14 16:40 UTC
hey,

would it be possible to integrate the [Inlining Analyzer ](https://github.com/szehetner/InliningAnalyzer) into rider?

cheers,
Wojtek

**Comment by auduchinok** [comment] 2017-12-17 11:34
@wklm From a brief look I don't think it'd be feasible without rewriting a part of the analyzer itself right now. If it was a ReSharper extension, it'd be relatively easy to make it work in Rider, but it is an extension for Visual Studio that relies on VS APIs that ReSharper (and, consequently, Rider) doesn't have.

Using custom Roslyn analyzers is planned for 2018.1 Rider release, so as soon as it's available adding such analyzer by a user should be possible.

**Comment by auduchinok** [comment] 2018-03-11 19:09
Closing as the question was answered.

**Closed by auduchinok** 2018-03-11 19:09 UTC

**Comment by pineapplemachine** [comment] 2024-11-01 08:07
Roslyn analyzers are now part of Rider, but they do not seem to include the functionality provided by the Inlining Analyzer, at least not that I was able to find in the settings.

https://www.jetbrains.com/help/rider/Using_NET_Compiler_Analyzers.html

Are there any plans to make inlining analysis available in Rider? I have some hot paths in my code where it would be helpful if I could quickly check in Rider if there's anything preventing calls from being inlined as intended.

**Comment by auduchinok** [comment] 2024-11-01 09:04
@pineapplemachine This is the F# plugin repo, and F# uses its own analysers SDK, not compatible with Roslyn. For questions about Roslyn integration in Rider please file an issue on [YouTrack](https://youtrack.jetbrains.com/issues/RIDER).

**Comment by pineapplemachine** [comment] 2024-11-01 09:56
Ahhh, my mistake. I came here from a search result and didn't realize where I'd ended up. Sorry about that!

**Comment by auduchinok** [comment] 2024-12-04 10:53
@pineapplemachine No problem, I'm happy to help!
