### ISSUE TITLE
F# files in the Solution Explorer are ordered alphabetically instead of the order specified in the project file

### ISSUE THREAD

**Issue by troykershaw** [JetBrains/fsharp-support#3] opened 2017-11-16 20:39 UTC
This makes it difficult to know and adjust compilation order.

To be clear, the order is correct when compiling, it's just the display that's incorrect.

Here's an example:
![image](https://user-images.githubusercontent.com/1085872/32914417-83ca4ad4-cae3-11e7-9647-b5fb83406bd1.png)

**Comment by vasily-kirichenko** [comment] 2017-11-16 20:48
@auduchinok I don’t think all issues from YouTrack should be duplicated here. Maybe just turn off issues here?

**Comment by troykershaw** [comment] 2017-11-17 05:49
If you plan on taking PRs turning issues off is not a good idea. It will greatly reduce discussion on issues and what can be done to fix them, especially if this problem can be fixed in this repo.

**Comment by auduchinok** [comment] 2017-11-20 10:05
@troykershaw This is a duplicate of the [issue](https://youtrack.jetbrains.com/issue/RIDER-7771) on Rider tracker. I'll leave this issue open until the existing one is fixed.

@vasily-kirichenko We've had an internal discussion before opening the repo regarding disabling GitHub issues and couldn't come to agreement. We ended up keeping it enabled for now to see how it goes.

**Comment by auduchinok** [comment] 2018-04-03 15:57
Fixed starting in https://github.com/JetBrains/fsharp-support/commit/47c51d21533e2edbf6a603f6d54a5b5496b94593.

**Closed by auduchinok** 2018-04-03 15:57 UTC
